### ISSUE TITLE
warning with peer dependencies

### ISSUE THREAD

**Issue by bianchijoao** [sugarshin/react-instagram-embed#271]
Hello. I'm facing a issue that even I remove the package and install later this warning keeps showing on my npm install:
> npm WARN react-instagram-embed@2.0.0 requires a peer of react@^16.0.0 || ^15.0.0 || ~0.14.0 but none is installed. You must install peer dependencies yourself.

And I'm using at the moment React 17.0.1.

Can someone give a little advice to how fix that?

**Comment by FelixButzbach** [comment]
@bianchijoao I see the same warning. This is because this package requires React 16, 15 or 0.14, but neither is installed. In my case because I am using React 17. 
As we are using react-instagram-embed in our codebase without problems, the fix might be as simple as bumping the peer dependencies like so:
 
`"peerDependencies": {
    "react": "^17.0.0 || ^16.0.0 || ^15.0.0 || ~0.14.0",
    "react-dom": "^17.0.0 || ^16.0.0 || ^15.0.0 || ~0.14.0"
  },`

But I can't test it at the moment, so it would be nice somebody from the maintainers to have a look.

Btw. this might also be the problem in this [issue](https://github.com/sugarshin/react-instagram-embed/issues/255)

**Comment by Luke4299** [comment]
> @bianchijoao I see the same warning. This is because this package requires React 16, 15 or 0.14, but neither is installed. In my case because I am using React 17.
> As we are using react-instagram-embed in our codebase without problems, the fix might be as simple as bumping the peer dependencies like so:
> 
> ```
> "peerDependencies": {
>     "react": "^17.0.0 || ^16.0.0 || ^15.0.0 || ~0.14.0",
>     "react-dom": "^17.0.0 || ^16.0.0 || ^15.0.0 || ~0.14.0"
> },
> ```
> 
> But I can't test it at the moment, so it would be nice somebody from the maintainers to have a look.
> 
> Btw. this might also be the problem in this [issue](https://github.com/sugarshin/react-instagram-embed/issues/255)



Has this worked for anyone?

**Comment by sugarshin** [comment]
It’s solved
