### ISSUE TITLE
Library not working

### ISSUE THREAD

**Issue by marijaantic** [sugarshin/react-instagram-embed#31]
**Bug noticed on live demo:** https://sugarshin.github.io/react-instagram-embed/

**Comment by yu-imu** [comment]
My application is also faced this bug.
This bug may be caused by CORB.
> search console
![screen shot 2018-10-28 at 22 59 50](https://user-images.githubusercontent.com/17560599/47648304-fecd4480-dbbc-11e8-9a84-0caeca783d9e.png)

**Comment by khairendra** [comment]
Yup, i also experienced this problem.
Probably because of the callback ?

in firefox if you access directly

`https://api.instagram.com/oembed/?hidecaption=false&maxwidth=320&omitscript=true&url=https%3A%2F%2Finstagr.am%2Fp%2FZw9o4%2F`

without the callback, it correctly return js object.

but if you also include the callback like
`https://api.instagram.com/oembed/?hidecaption=false&maxwidth=320&omitscript=true&url=https%3A%2F%2Finstagr.am%2Fp%2FZw9o4%2F&callback=__jp0`,

it return `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Comment by hugovk** [comment]
Here's a PR to fix it: https://github.com/sugarshin/react-instagram-embed/pull/32.

**Comment by JokinenK** [comment]
Before this PR gets merged or bug fixed in some other way, here is easy way to test the PR's changes out:

npm install --save git+https://github.com/JokinenK/react-instagram-embed#release/1.4.0_json

or 

yarn add git+https://github.com/JokinenK/react-instagram-embed#release/1.4.0_json

**Comment by sugarshin** [comment]
I solved and released new version.
